import type { Metadata } from 'next'

/**
 * Canonical site origin. Uses the www host because the apex
 * (esmbusinessschool.com) 308-redirects to www at the DNS/Vercel layer.
 * Override with NEXT_PUBLIC_SITE_URL if the domain ever changes.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || 'https://www.esmbusinessschool.com'
).replace(/\/$/, '')

export const SITE_NAME = 'ESM Business School'

export const SITE_DESCRIPTION =
  'ESM Business School delivers accredited British qualifications — undergraduate and postgraduate diplomas in business, technology and health & social care, studied flexibly online or blended from our home in the UAE.'

type PageMetaInput = {
  title: string
  description?: string
  /** Path beginning with "/", e.g. "/about". Defaults to the home page. */
  path?: string
}

/** Alt text for the shared social card. */
const OG_ALT = 'ESM Business School — Accredited British Qualifications'

/**
 * Shared social-card image, generated by the `opengraph-image` /
 * `twitter-image` routes in `src/app`. When a page exports its own `openGraph`
 * object, Next.js does NOT auto-inherit the root image file, so it must be
 * referenced explicitly here. Relative URLs are resolved against `metadataBase`.
 */
const OG_IMAGE = { url: '/opengraph-image', width: 1200, height: 630, alt: OG_ALT }
const TWITTER_IMAGE = { url: '/twitter-image', width: 1200, height: 630, alt: OG_ALT }

/**
 * Build per-page metadata: title, description, canonical URL, Open Graph and
 * Twitter card (including the shared social-share image).
 */
export function pageMetadata({ title, description, path = '/' }: PageMetaInput): Metadata {
  const url = `${SITE_URL}${path}`
  const desc = description ?? SITE_DESCRIPTION
  const ogTitle = `${title} | ${SITE_NAME}`

  return {
    title,
    description: desc,
    alternates: { canonical: url },
    openGraph: {
      type: 'website',
      siteName: SITE_NAME,
      title: ogTitle,
      description: desc,
      url,
      locale: 'en_US',
      images: [OG_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle,
      description: desc,
      images: [TWITTER_IMAGE],
    },
  }
}
