import { ImageResponse } from 'next/og'

export const size = { width: 64, height: 64 }
export const contentType = 'image/png'

// Favicon: gold "E" monogram on the brand navy, generated by next/og.
export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          background: '#1B2A4A',
          color: '#D4891A',
          fontSize: 42,
          fontWeight: 800,
          fontFamily: 'sans-serif',
          borderRadius: 12,
        }}
      >
        E
      </div>
    ),
    { ...size }
  )
}
